### ISSUE TITLE
CSS universal selector is too aggressive

### ISSUE THREAD

**Issue by red-meadow** [Tom-Rawlings/Resizable.js#8]
Hi. Thank you for the great work!

This CSS rule seems to be too aggressive and affects other parts of the page:
```css
* {
  padding: 0;
  margin: 0;
  top: 0;
  left: 0;
}
```

In my case it broke the positioning of the element with `position: absolute` and `right: 0`.
